### ISSUE TITLE
Change License

### ISSUE THREAD

**Issue by markusguenther** [Unikka/neos-linkchecker#19]
As it is a neos package and neos is under GPL-3 so we need to use the license as well.

**Comment by soham4abc** [comment]
I can work on this issue
If possible pls assign

**Comment by markusguenther** [comment]
Hello,

thanks for that offer :)
Feel free to change it ❤️

**Comment by soham4abc** [comment]
> Hello,
> 
> thanks for that offer :)
> Feel free to change it ❤️

the MIT license needs to be replaced with GPL-3 right?

**Comment by markusguenther** [comment]
Indeed

**Comment by soham4abc** [comment]
> Indeed

I am on it!

**Comment by soham4abc** [comment]
@markusguenther  it's done!

**Comment by rolandschuetz** [comment]
I'm curious, also for my own open source packages, why can't we use MIT for this?

**Comment by markusguenther** [comment]
It is a Neos package and Neos is GPL and has copy left, therefore this package needs to be GPL itself ...
As flow is MIT a pure flow package can be MIT for instance.

So without the backend module it could be MIT maybe.
