### ISSUE TITLE
Neos 8 compatibility

### ISSUE THREAD

**Issue by simonschaufi** [Unikka/neos-linkchecker#31]
It would be great if this package would be compatible with PHP 8.1 and Neos 8

**Comment by markusguenther** [comment]
Do you still use it, or did you switch to https://github.com/code-q-web-factory/CodeQ.LinkChecker
Because I build the package in 2018 as a test and never polished it.

As Roland now added the missing pieces, my motivation to finish that is pretty low ;)
Because I don't use it.
