### ISSUE TITLE
Version for Neos 5

### ISSUE THREAD

**Issue by jonnitto** [Unikka/neos-linkchecker#7]

**Comment by markusguenther** [comment]
Need to check this as I did not use the package.

**Comment by kdambekalns** [comment]
I just ran `dev-master` in a Neos 5.3 setup, and crawling worked fine, as did the management module. So I think a tag would solve this…

**Comment by markusguenther** [comment]
Thanks for testing. To be honest that package was a quick shot for a Noerdisch customer and as the project never went live it is not really maintained. But if there is a need I will give it a try and polish it a bit ;)

**Comment by rolandschuetz** [comment]
https://github.com/Unikka/neos-linkchecker/pull/17

**Comment by markusguenther** [comment]
Created a new 1.1 tag... 

Guess will add semantic-release and so on like in my other packages, when I see that this is now used somewhere ;)
